"""Data Transfer Objects (DTO) for the Presentation API layer."""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class PresentationResult(BaseModel):
    """A flattened, UI-friendly representation of a recommended restaurant."""

    name: str = Field(..., description="Restaurant display name.")
    cuisines: str = Field(..., description="Comma-separated cuisines.")
    rating: Optional[float] = Field(None, description="Aggregate rating.")
    cost: Optional[str] = Field(None, description="Cost bucket (low/medium/high).")
    explanation: str = Field(..., description="AI-generated rationale.")


class PresentationResponse(BaseModel):
    """The overarching response sent to the web UI."""

    results: List[PresentationResult] = Field(..., description="Ranked list of restaurants.")
    summary_blurb: Optional[str] = Field(
        None,
        description="A short, catchy summary of the recommendations generated by Groq.",
    )
